pub mod wdf_wrapper;

#[allow(
    unused_unsafe,
    unsafe_op_in_unsafe_fn,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    clippy::all
)]
#[allow(warnings)]
pub mod ndis {
    pub use wdk_sys::{GUID, HANDLE, PMDL};

    pub const AF_INET: u32 = 2;
    pub const AF_INET6: u32 = 23;
    pub const RPC_C_AUTHN_DEFAULT: i32 = -1i32;

    // Use concat! and env! macros to dynamically get the file path generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/ndis_bindings.rs"));

    pub unsafe fn NET_BUFFER_DATA_LENGTH(nb: PNET_BUFFER) -> ULONG {
        (*nb)
            .__bindgen_anon_1
            .__bindgen_anon_1
            .__bindgen_anon_1
            .DataLength
    }

    pub unsafe fn NET_BUFFER_NEXT_NB(nb: PNET_BUFFER) -> PNET_BUFFER {
        (*nb).__bindgen_anon_1.__bindgen_anon_1.Next
    }

    pub unsafe fn NET_BUFFER_CURRENT_MDL(nb: PNET_BUFFER) -> *mut MDL {
        (*nb).__bindgen_anon_1.__bindgen_anon_1.CurrentMdl
    }

    pub unsafe fn NET_BUFFER_CURRENT_MDL_OFFSET(nb: PNET_BUFFER) -> ULONG {
        (*nb).__bindgen_anon_1.__bindgen_anon_1.CurrentMdlOffset
    }


    pub unsafe fn NET_BUFFER_DATA_OFFSET(nb: PNET_BUFFER) -> ULONG {
        (*nb).__bindgen_anon_1.__bindgen_anon_1.DataOffset
    }

    pub unsafe fn NET_BUFFER_LIST_NEXT_NBL(nbl: PNET_BUFFER_LIST) -> PNET_BUFFER_LIST {
        (*nbl).__bindgen_anon_1.__bindgen_anon_1.Next
    }
    
    pub unsafe fn NET_BUFFER_LIST_FIRST_NB(nbl: PNET_BUFFER_LIST) -> PNET_BUFFER {
        (*nbl).__bindgen_anon_1.__bindgen_anon_1.FirstNetBuffer
    }
}

#[allow(non_snake_case)]
pub mod ntddk {
    use crate::wdk_ext::ndis::{ KPROCESSOR_MODE, PVOID};
    use core::ptr::null_mut;
    use crate::log;
    use wdk::{println,print};

    pub fn MmGetSystemAddressForMdlSafe(mdl: wdk_sys::PMDL, priority: wdk_sys::ULONG) -> PVOID {
        unsafe {
            if ((*mdl).MdlFlags
                & ((wdk_sys::MDL_MAPPED_TO_SYSTEM_VA | wdk_sys::MDL_SOURCE_IS_NONPAGED_POOL)
                    as wdk_sys::CSHORT)
                != 0)
            {
                (*mdl).MappedSystemVa
            } else {
                log!("[debug]: MmGetSystemAddressForMdlSafe NOT mapped to system VA");

                wdk_sys::ntddk::MmMapLockedPagesSpecifyCache(
                    mdl,
                    wdk_sys::_MODE::KernelMode as KPROCESSOR_MODE,
                    wdk_sys::_MEMORY_CACHING_TYPE::MmCached,
                    null_mut(),
                    0,
                    priority,
                )
            }
        }
    }
}

#[allow(
    unused_unsafe,
    unsafe_op_in_unsafe_fn,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    clippy::all
)]
#[allow(warnings)]
pub mod flt {
    pub use wdk_sys::{GUID, HANDLE, PMDL};
    include!(concat!(env!("OUT_DIR"), "/flt_bindings.rs"));
}
